"""empty message

Revision ID: 8032b4ed1dd3
Revises: bcd7b02339ac
Create Date: 2020-12-15 20:59:36.154511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8032b4ed1dd3'
down_revision = 'bcd7b02339ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('testi', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'testi')
    # ### end Alembic commands ###
