"""empty message

Revision ID: ca294b36defd
Revises: 8032b4ed1dd3
Create Date: 2020-12-15 21:06:22.349200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca294b36defd'
down_revision = '8032b4ed1dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'testi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('testi', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
